action_id: trunk-whoami
date: 2024-04-28 01:47:39
run: trunk whoami
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1714268859
full_timestamp:
  nanos: 578930000
  seconds: 1714268859
trunk_version: 1.21.0
