action_id: trunk-whoami
date: 2024-04-30 15:55:32
run: trunk whoami
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1714492532
full_timestamp:
  nanos: 112491000
  seconds: 1714492532
trunk_version: 1.21.0
