action_id: trunk-whoami
date: 2024-04-23 03:48:53
run: trunk whoami
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1713844133
full_timestamp:
  nanos: 1926000
  seconds: 1713844133
trunk_version: 1.21.0
