action_id: trunk-upgrade-available
date: 2024-04-23 14:07:28
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1713881248
full_timestamp:
  nanos: 298967000
  seconds: 1713881248
trunk_version: 1.21.0
