action_id: trunk-upgrade-available
date: 2024-05-03 08:22:41
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1714724561
full_timestamp:
  nanos: 700245000
  seconds: 1714724561
trunk_version: 1.21.0
