action_id: trunk-upgrade-available
date: 2024-05-02 03:33:26
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1714620806
full_timestamp:
  nanos: 158739000
  seconds: 1714620806
trunk_version: 1.21.0
