action_id: trunk-share-with-everyone
date: 2024-05-02 02:51:51
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1714618311
full_timestamp:
  nanos: 10398000
  seconds: 1714618311
trunk_version: 1.21.0
