action_id: trunk-cache-prune
date: 2024-04-22 02:17:30
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1713752250
full_timestamp:
  nanos: 466510000
  seconds: 1713752250
trunk_version: 1.21.0
