action_id: trunk-cache-prune
date: 2024-04-28 10:50:16
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1714301416
full_timestamp:
  nanos: 2490000
  seconds: 1714301416
trunk_version: 1.21.0
