action_id: trunk-single-player-auto-on-upgrade
date: 2024-05-02 02:53:54
run: trunk on-upgrade --single-player-only -n --no-progress --allow-daemon-start=false --print-summary --scope=check,plugins,runtimes,tools
run_from: ""
trigger: schedule 24h+5m
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1714618434
full_timestamp:
  nanos: 640442000
  seconds: 1714618434
trunk_version: 1.21.0
